### ISSUE TITLE
Conflict with special fields

### ISSUE THREAD

**Issue by AnKingMed** [Arthur-Milchior/anki-export-from-browser#6]
I was messing with this and realized a past version of this add-on that I have still works perfectly (I'm currently on 2.1.19) and it does not conflict with the special fields add-on.  Is there a reason for the new update?   I attached the version I'm using
[1983204951*.zip](https://github.com/Arthur-Milchior/anki-export-from-browser/files/4109532/1983204951.zip)

**Comment by Arthur-Milchior** [comment]
Hi

As I told on ankiweb, can you please tell me exactly what conflict you're talking about ?
Is there an error message ? If so can you copy/paste it ?
Does it just stop working ?


Thanks for giving me the past code. github allow mo to have copy of all past verison, so no problem here

There have been no update since november. So I'm surprised that you have a problem which occurs now.

**Comment by AnKingMed** [comment]
If special fields is toggled on, the current version will not export correctly (just doesn't work).  The whole collection will be exported instead of just your selection. I'm currently using the version I attached above on Anki 2.1.20beta5 and it is working fine, including if I have special fields turned on

**Comment by Arthur-Milchior** [comment]
I fear I spent far too much time looking at the difference between versions. But I think I know have a correct idea of why the previous version worked and not the current one.

Both "special fields" and "export from browser" change the way cards are exported.
Both "special fields" and the previous version you are currently using of "export from browser" makes BIG changes. Both just deleted the previous method `exportInto` and replace it by something totally new. It means that you'll get either "special fields" or "export from browser". It seems that "export from browser" now works for you because it wins this fight. "special fields" come first, it delete the previous `exportInto` and replace it by its version. But then your version of `export from browser` comes, delete the version of `exportInto` used by "special fields" and replace by its own version.

I honestly have no clue what "special fields" does, neither the add-on page nor the github page makes sens to me. But I'm pretty sure that if you check, you'll find that "special fields" exporting is now broken. And it's not only broken if you export from browser, it's broken whatever kind of exporting you do. Can you please test and confirm my intuition ?

The change I made to the add-on some months ago ensured that instead of "deleting everything and replacing by my version" I just made small changes. I made the changes I needed, and nothing else.
The previous version, the one you currently use, is extremely ugly, and is bad code practice.
The code of "special fields" is also ugly and bad code practice too, for the same reason. One reason why it's "bad" is because they way I used to code, and the way "special fields" is coded ensure that it's impossible to make both add-on incompatibles.
Note that I'm not stating that there is an easy way to make add-on compatibles. I honestly don't know, since I don't want to spend time looking at his code and I don't know what he is doing.

Can you please either tell me what "special fields" is supposed to do. Or a link to a place explaining it. 
I did find your video "https://www.youtube.com/watch?v=frK8fzLjrEU", and while I understand why importing need to be changed, I don't get why it changes the export method.
Note that you could extremely easily use add-on config instead of editing directly the code. This way, you would not have to restart anki each time. This is actually something which I could code in less than 20 minutes I believe. But of course, it requires using 2.1

**Comment by AnKingMed** [comment]
I never understood why special fields modified exporting either.  Special fields was made for people using premade decks so they could get updates from other people without losing their own edits. For example, if someone were to import a newer version of a deck without the addon, it would overwrite everything completely. For my medical school deck, I have a cloze field with the usual “Text” and “Extra” fields but also a “lecture notes” field. If someone chooses to protect the “lecture notes” field with the special fields addon, then the text and extra field will update and overwrite, but the lecture notes field remains the same.  There is also an option to merge tags or overwrite tags which is very important. As I said, I don’t know why it modifies exporting, but it works well for what it was designed to do.  I have many ideas on how it could be made much simpler for users (like the config you mentioned) but I haven’t found anyone willing to improve it and I have no coding experience myself.  In the medical school world, this is currently one of the most important add-ons.  The biggest confusing point of this process is that the deck being imported will only update cards if the imported deck has a newer timestamp on it (i.e. it was changed more recently).  Because people are always changing their decks, the best method I've ever found is to import the update deck into a new profile then do something to every card to make it "newer" (i.e. add a tag to all cards and then delete the tag). Then export that deck and then it can be imported into the main profile to update the users current deck.  Ideally there would be an add-on that read the import and noticed there were cards with matching note IDs and allowed the user to choose which deck they wanted each field from (i.e. they want the text and extra field from the imported deck, but they want the lecture notes field from the current deck).  If this is something you could code in 20 min, perhaps it would be something worth trying to do and throw it on your patreon or just share. There are many inexperienced med student Anki users that would love something that is more user friendly.  Feel free to email me- ankingmed@gmail.com

As far as the conflict betwen special fields and export selected cards, I'll just keep the older version of export selected cards because it makes my life easier, but I understand your reasoning for updating it

**Comment by Arthur-Milchior** [comment]
I fear I was not clear.
What I could code in 20 minutes is: ensuring that instead of modifying the code, you use the standard way for anki to configure deck. This would have two advantages:
* you will directly see the line(s) you have to edit
* you don't have to restart anki to use the new configuration

what would take more than 20 minutes however is, either, creating the pull request and waiting for the original add-on author to merge my pull request (or explains why he rejects it)
or if they are not here anymore, then update the add-on myself, and in this case create a correct documentation.

Other things which would be simple to do for me:
* modify the add-on so that it does not change export (or so that this can be configured in anki)
* update unconditionally. Ignore the modification date. Once again, it can be somethig which is configured in the add-on configuration

Things which would be simple to do for you:
* ask original add-on author why they changed the exporting method. And so figure out whether it can create a problem to just ignore this change. I suspect that if they took time to do so much work, there is a purpose. Even if they didn't document this purpose


By the way, I've got a bad news for you. There is an error in your video. What is taken into account to know whether a note is a duplicate is note the "note id". That would make a lot of sens, and this is a mistake I made myself some time ago. That actually was the cause of a bug that I had a lot of trouble to debug in my add-on "copy note" (because for some reason, copied note would not be imported but would be detected as double even if they had different note id)
What is considered for importing purpose is the note GUID (globally unique id). You can't have access to this value without using the "advanced browser" addon (disclosure: I participated to this add-on) or the debugger. I have absolutely NO IDEA why Damien used two different ideas, the note idea, and the GUID. But for some reason, note idea are used everywhere EXCEPT for importing purpose, where GUID are used instead.

**Comment by AnKingMed** [comment]
Ah I understand now. Thank you for explaining that to me and the tidbit about the GUID. 

Unfortunately I have not been able to contact the author in months. I just sent him an email so we’ll see. I looked over the documentation and I remember the export thing now- the author wanted to make it so you could export cards without your personal notes if you wanted. Personally I’ve never used it and I don’t know anyone that does. 

If you do have 20 min and are willing, I would absolutely love to be able to configure the add-on in the config and update unconditionally (this would be HUGE!). Having an option to choose whether or not it modifies export would be nice just for compatibility with this export selected cards add-on.  I’d be happy to test this for you and even shoot $20 your way as a thank you. If the original author doesn’t respond, you could release it separately- I’ll let you know if I hear from them

**Comment by Arthur-Milchior** [comment]
Do you know how to use an add-on from github ? Doing the code is easy. Packaging takes more time, and I've actually never used the forma .ankiaddons that glutanimate created and added to anki.

I certainly see the point of being able to remove some informations while exporting. I don't like the way he does it. I think you could do it in a cleaner way. But I'm not going to work on it, since I've no reason to want it currently. 
Do you means 20$ by features, or 20 for all features I mentionned ?
You may have seen on ankiweb that I can't use Venmo. Paypal is fine for me

**Comment by AnKingMed** [comment]
Yeah I know how to make a .ankiaddon file

Unfortunately, I really don't have much so all I can offer is $20 (and I can do paypal/patreon or whatever works). The features I want most are being able to configure the add-on in the config and update unconditionally.  The rest would all be nice, but isn't necessary.   I can also share your patreon on my instagram with everyone using my medical school deck and suggest they donate a couple bucks as its making their lives easier too.

**Comment by Arthur-Milchior** [comment]
Please, try https://github.com/Arthur-Milchior/SpecialFields and check whether special fields works with the change you requested.
You can find my ko-fi link in the main page of this add-on on github. 

I removed the "exporting" part. I believe it should be in another add-on. This means that the current version of "export from browser" and my fork of "special fields" should be able to work together correctly.

Please, if there are any trouble which is not related to "export from browser", post about it in a bug report in my fork of special field
